// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbwhgmppisiexfzwxxtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxid2hnbXBwaXNpZXhmend4eHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjE1MjMsImV4cCI6MjA3MDMzNzUyM30.0b-P6uC2d2GyND4ixgB_7WKGsfhjg1XJk2bTRhc8axA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});